# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

######################################################################
# Site Configuration Config
######################################################################

# Global Site Title
title:             Translational Genomics Laboratory

description:       > # this means to ignore newlines until "baseurl:"
  TGL enhances rapid access to genomics technologies, and facilitates genomic interpretation and reporting in clinical oncology.

# Contact Information
email:             dax.torti@oicr.on.ca

# the subpath of your site, e.g. /blog
baseurl: ""

# Default permalink for posts
permalink: /node/:year-:month-:day-:title.html

# Post excerpt tag https://jekyllrb.com/docs/posts/#post-excerpts
excerpt_separator: "<!--more-->"

######################################################################
# Collections setting. https://jekyllrb.com/docs/collections/
######################################################################

collections:
  # Default collections
  _images:
    output: true
  _pages:
    output: true
  _privateFiles:
    output: true
  _files:
    output: true
  _videos:
    output: true
  _weblinks:
    output: true
  _modules:
    output: true
  _emailtpl:
    output: false
  _members:
    output: false
  _publications:
    output: false
  _banner:
    output: true
  # Custom collections
  _cats:
    output: true
  _dogs:
    output: true
  _abstracts:
    output: true

defaults:
  # Default
  - scope:
      path: ""
      type: _weblinks
    values:
      layout: weblinks
      published: true
  - scope:
      path: ''
      type: _modules
    values:
      title: ''
      date_tdt: '2018-07-11T19:36:04.633Z'
      author: ''
      layout: default
      permalink: '/_modules/:name/'
      published: true
      isPublic_b: false
    required: []
    validate: {}
    labels:
      title: Title
      date_tdt: Date
      author: Author
      layout: Layout
      permalink: Permanent Link
      published: Published
      isPublic_b: Public
  - scope:
      path: ""
      type: _files
    values:
      layout: files
      published: true
  - scope:
      path: ""
      type: _privateFiles
    values:
      layout: privateFiles
      published: true
  - scope:
      path: ""
      type: _emailtpl
    values:
      layout: emailtpl
  - scope:
      path: ""
      type: _videos
    values:
      layout: videos
      published: true
  - scope:
      path: ""
      type: _images
    values:
      layout: images
      published: true
  - scope:
      path: ""
      type: "members"
    values:
      title: Team | OICR Labs
    required: 
      - firstName_txt
      - lastName_txt
      - group_txt
      - order
  - scope:
      path: ""
      type: "publications"
    values:
      title: Publications | OICR Labs
    required: 
      - title_txt
      - publicationType_txt
  - scope:
      path: ""
      type: _banner
    values:
      layout: banner
#Custom collections
  #BREEDS
  - scope:
      path: "" # an empty string here means all files in the project
      type: _cats
    values:
      title: ""
      author: ""
      layout: cats
      permalink: "/cats/:name/"
      published: true
      isPublic_b: true
      image_img: ""
      breed_txt: ""
      hairType_txt: ""
      trait_txt: ""
      playfullness_txt: ""
      intelligence_txt: ""
      category_list:
        - category_txt: ""
    labels: 
      title: Title
      author: Author
      layout: Layout
      permalink: Permanent Link
      published: Published
      isPublic_b: Public
      image_img: Picture
      breed_txt: Cat Breed Name
      hairType_txt: Hair Type
      trait_txt: Defining Trait
      playfullness_txt: Playfullness Level
      intelligence_txt: Intelligence Level
      category_list: Category List
      category_txt: Category List Item
  - scope:
      path: "" # an empty string here means all files in the project
      type: _dogs
    values:
      title: ""
      author: ""
      layout: dogs
      permalink: "/dogs/:name/"
      published: true
      isPublic_b: true
      image_img: ""
      breed_txt: ""
      hairType_txt: ""
      trait_txt: ""
      playfullness_txt: ""
      intelligence_txt: ""
      category_list:
        - category_txt: ""
    labels: 
      title: Title
      author: Author
      layout: Layout
      permalink: Permanent Link
      published: Published
      isPublic_b: Public
      image_img: Picture
      breed_txt: Cat Breed Name
      hairType_txt: Hair Type
      trait_txt: Defining Trait
      playfullness_txt: Playfullness Level
      intelligence_txt: Intelligence Level
      category_list: Category List
      category_txt: Category List Item
# Custom collections
  # ABSTRACTS
  - scope:
      path: ''
      type: _abstracts
    values:
      title: ''
      author: ''
      layout: abstract_details
      permalink: '/abstracts/:name/'
      published: true
      isPublic_b: true
      tabTitle_txt: 'Abstract Details'
      posternumber_ti: ''
      categories_list:
        - category_txt: ''
      keywords_txt: ''
      authors_list:
        - authors_txt: ''
          reference: ''
      affiliations_list:
        - affiliation_txt: ''
          reference: ''
      presenting-author_txt: ''
      presenting-author-email_txt: ''
      presenting-author-title_txt: ''
      text_txt: ''
    required: []
    validate: {}
    labels:
      title: Title
      author: Author
      layout: Layout
      permalink: Permanent Link
      published: Published
      isPublic_b: Public
      tabTitle_txt: Tab Title
      posternumber_ti: Poster Number
      categories_list: Category List
      categories_list.category_txt: Category List Item
      keywords_txt: Keywords
      authors_list: List of Authors
      authors_list.author_txt: Author
      affiliations_list: List of Affiliations
      affiliations_list.affiliation_txt: Author Affiliation
      presenting-author_txt: Presenting Author Name
      presenting-author-email_txt: Presenting Author Email
      presenting-author-title_txt: Presenting Author Title
      text_txt: Abstract Text      


######################################################################
# Jekyll Environment Config
######################################################################

# ImageFile Path
imagePath: /assets/site/images/

# Build settings
markdown: kramdown

# Jekyll plugins ( also requires to add list in Gemfile )
plugins:

# Exclude these files when the site is generated.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - webpack.config.js
  - .eslint
  - package.json
  - npm-debug.log
  - vendor
  - docker-compose.yml
  - start.sh
  - start-build.sh
  - start-preview.sh
  - baseline-update

theme: jekyll-theme-minimal

