<!-- Bootstrap JS -->
<!-- jQuery first, then Bootstrap JS. -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.0/jquery.min.js"></script>
<script type="text/javascript" src="/assets/core/js/bootstrap-3.3.7.min.js"></script> 


<!-- Bundle JS -->
<!-- JavaScript -->
<script type="text/javascript" src="/assets/site/js/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="/assets/core/js/app_default.js"></script>
<script type="text/javascript" src="/assets/site/js/test2.js"></script>
